#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: 356da62
#
# Source0 file verified with key 0x0579D69772CD9B22 (jdemel@gnuradio.org)
#
Name     : volk
Version  : 3.1.2
Release  : 2
URL      : https://www.libvolk.org/releases/volk-3.1.2.tar.gz
Source0  : https://www.libvolk.org/releases/volk-3.1.2.tar.gz
Source1  : https://www.libvolk.org/releases/volk-3.1.2.tar.gz.asc
Source2  : 0579D69772CD9B22.pkey
Summary  : VOLK: Vector Optimized Library of Kernels
Group    : Development/Tools
License  : Apache-2.0 LGPL-3.0
Requires: volk-bin = %{version}-%{release}
Requires: volk-lib = %{version}-%{release}
Requires: volk-license = %{version}-%{release}
Requires: volk-python = %{version}-%{release}
Requires: volk-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : orc-dev
BuildRequires : pkg-config
BuildRequires : pypi-mako
BuildRequires : python3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://travis-ci.com/gnuradio/volk.svg?branch=master)](https://travis-ci.com/gnuradio/volk) [![Build status](https://ci.appveyor.com/api/projects/status/5o56mgw0do20jlh3/branch/master?svg=true)](https://ci.appveyor.com/project/gnuradio/volk/branch/master)
![Check PR Formatting](https://github.com/gnuradio/volk/workflows/Check%20PR%20Formatting/badge.svg)
![Run VOLK tests](https://github.com/gnuradio/volk/workflows/Run%20VOLK%20tests/badge.svg)
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3360942.svg)](https://doi.org/10.5281/zenodo.3360942)

%package bin
Summary: bin components for the volk package.
Group: Binaries
Requires: volk-license = %{version}-%{release}

%description bin
bin components for the volk package.


%package dev
Summary: dev components for the volk package.
Group: Development
Requires: volk-lib = %{version}-%{release}
Requires: volk-bin = %{version}-%{release}
Provides: volk-devel = %{version}-%{release}
Requires: volk = %{version}-%{release}

%description dev
dev components for the volk package.


%package lib
Summary: lib components for the volk package.
Group: Libraries
Requires: volk-license = %{version}-%{release}

%description lib
lib components for the volk package.


%package license
Summary: license components for the volk package.
Group: Default

%description license
license components for the volk package.


%package python
Summary: python components for the volk package.
Group: Default
Requires: volk-python3 = %{version}-%{release}

%description python
python components for the volk package.


%package python3
Summary: python3 components for the volk package.
Group: Default
Requires: python3-core

%description python3
python3 components for the volk package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 0579D69772CD9B22' gpg.status
%setup -q -n volk-3.1.2
cd %{_builddir}/volk-3.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722358161
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722358161
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/volk
cp %{_builddir}/volk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/volk/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
cp %{_builddir}/volk-%{version}/cpu_features/LICENSE %{buildroot}/usr/share/package-licenses/volk/05c9c329f6de4edcdc6d2e84fa466aaaeef3166f || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/volk-config-info
/usr/bin/volk_modtool
/usr/bin/volk_profile

%files dev
%defattr(-,root,root,-)
/usr/include/volk/constants.h
/usr/include/volk/saturation_arithmetic.h
/usr/include/volk/volk.h
/usr/include/volk/volk_16i_32fc_dot_prod_32fc.h
/usr/include/volk/volk_16i_branch_4_state_8.h
/usr/include/volk/volk_16i_convert_8i.h
/usr/include/volk/volk_16i_max_star_16i.h
/usr/include/volk/volk_16i_max_star_horizontal_16i.h
/usr/include/volk/volk_16i_permute_and_scalar_add.h
/usr/include/volk/volk_16i_s32f_convert_32f.h
/usr/include/volk/volk_16i_x4_quad_max_star_16i.h
/usr/include/volk/volk_16i_x5_add_quad_16i_x4.h
/usr/include/volk/volk_16ic_convert_32fc.h
/usr/include/volk/volk_16ic_deinterleave_16i_x2.h
/usr/include/volk/volk_16ic_deinterleave_real_16i.h
/usr/include/volk/volk_16ic_deinterleave_real_8i.h
/usr/include/volk/volk_16ic_magnitude_16i.h
/usr/include/volk/volk_16ic_s32f_deinterleave_32f_x2.h
/usr/include/volk/volk_16ic_s32f_deinterleave_real_32f.h
/usr/include/volk/volk_16ic_s32f_magnitude_32f.h
/usr/include/volk/volk_16ic_x2_dot_prod_16ic.h
/usr/include/volk/volk_16ic_x2_multiply_16ic.h
/usr/include/volk/volk_16u_byteswap.h
/usr/include/volk/volk_16u_byteswappuppet_16u.h
/usr/include/volk/volk_32f_64f_add_64f.h
/usr/include/volk/volk_32f_64f_multiply_64f.h
/usr/include/volk/volk_32f_8u_polarbutterfly_32f.h
/usr/include/volk/volk_32f_8u_polarbutterflypuppet_32f.h
/usr/include/volk/volk_32f_accumulator_s32f.h
/usr/include/volk/volk_32f_acos_32f.h
/usr/include/volk/volk_32f_asin_32f.h
/usr/include/volk/volk_32f_atan_32f.h
/usr/include/volk/volk_32f_binary_slicer_32i.h
/usr/include/volk/volk_32f_binary_slicer_8i.h
/usr/include/volk/volk_32f_convert_64f.h
/usr/include/volk/volk_32f_cos_32f.h
/usr/include/volk/volk_32f_exp_32f.h
/usr/include/volk/volk_32f_expfast_32f.h
/usr/include/volk/volk_32f_index_max_16u.h
/usr/include/volk/volk_32f_index_max_32u.h
/usr/include/volk/volk_32f_index_min_16u.h
/usr/include/volk/volk_32f_index_min_32u.h
/usr/include/volk/volk_32f_invsqrt_32f.h
/usr/include/volk/volk_32f_log2_32f.h
/usr/include/volk/volk_32f_null_32f.h
/usr/include/volk/volk_32f_s32f_32f_fm_detect_32f.h
/usr/include/volk/volk_32f_s32f_add_32f.h
/usr/include/volk/volk_32f_s32f_calc_spectral_noise_floor_32f.h
/usr/include/volk/volk_32f_s32f_clamppuppet_32f.h
/usr/include/volk/volk_32f_s32f_convert_16i.h
/usr/include/volk/volk_32f_s32f_convert_32i.h
/usr/include/volk/volk_32f_s32f_convert_8i.h
/usr/include/volk/volk_32f_s32f_convertpuppet_8u.h
/usr/include/volk/volk_32f_s32f_mod_rangepuppet_32f.h
/usr/include/volk/volk_32f_s32f_multiply_32f.h
/usr/include/volk/volk_32f_s32f_normalize.h
/usr/include/volk/volk_32f_s32f_power_32f.h
/usr/include/volk/volk_32f_s32f_s32f_mod_range_32f.h
/usr/include/volk/volk_32f_s32f_stddev_32f.h
/usr/include/volk/volk_32f_s32f_x2_clamp_32f.h
/usr/include/volk/volk_32f_s32f_x2_convert_8u.h
/usr/include/volk/volk_32f_sin_32f.h
/usr/include/volk/volk_32f_sqrt_32f.h
/usr/include/volk/volk_32f_stddev_and_mean_32f_x2.h
/usr/include/volk/volk_32f_tan_32f.h
/usr/include/volk/volk_32f_tanh_32f.h
/usr/include/volk/volk_32f_x2_add_32f.h
/usr/include/volk/volk_32f_x2_divide_32f.h
/usr/include/volk/volk_32f_x2_dot_prod_16i.h
/usr/include/volk/volk_32f_x2_dot_prod_32f.h
/usr/include/volk/volk_32f_x2_fm_detectpuppet_32f.h
/usr/include/volk/volk_32f_x2_interleave_32fc.h
/usr/include/volk/volk_32f_x2_max_32f.h
/usr/include/volk/volk_32f_x2_min_32f.h
/usr/include/volk/volk_32f_x2_multiply_32f.h
/usr/include/volk/volk_32f_x2_pow_32f.h
/usr/include/volk/volk_32f_x2_powpuppet_32f.h
/usr/include/volk/volk_32f_x2_s32f_interleave_16ic.h
/usr/include/volk/volk_32f_x2_subtract_32f.h
/usr/include/volk/volk_32f_x3_sum_of_poly_32f.h
/usr/include/volk/volk_32fc_32f_add_32fc.h
/usr/include/volk/volk_32fc_32f_dot_prod_32fc.h
/usr/include/volk/volk_32fc_32f_multiply_32fc.h
/usr/include/volk/volk_32fc_accumulator_s32fc.h
/usr/include/volk/volk_32fc_conjugate_32fc.h
/usr/include/volk/volk_32fc_convert_16ic.h
/usr/include/volk/volk_32fc_deinterleave_32f_x2.h
/usr/include/volk/volk_32fc_deinterleave_64f_x2.h
/usr/include/volk/volk_32fc_deinterleave_imag_32f.h
/usr/include/volk/volk_32fc_deinterleave_real_32f.h
/usr/include/volk/volk_32fc_deinterleave_real_64f.h
/usr/include/volk/volk_32fc_index_max_16u.h
/usr/include/volk/volk_32fc_index_max_32u.h
/usr/include/volk/volk_32fc_index_min_16u.h
/usr/include/volk/volk_32fc_index_min_32u.h
/usr/include/volk/volk_32fc_magnitude_32f.h
/usr/include/volk/volk_32fc_magnitude_squared_32f.h
/usr/include/volk/volk_32fc_s32f_atan2_32f.h
/usr/include/volk/volk_32fc_s32f_deinterleave_real_16i.h
/usr/include/volk/volk_32fc_s32f_magnitude_16i.h
/usr/include/volk/volk_32fc_s32f_power_32fc.h
/usr/include/volk/volk_32fc_s32f_power_spectral_densitypuppet_32f.h
/usr/include/volk/volk_32fc_s32f_power_spectrum_32f.h
/usr/include/volk/volk_32fc_s32f_x2_power_spectral_density_32f.h
/usr/include/volk/volk_32fc_s32fc_multiply2_32fc.h
/usr/include/volk/volk_32fc_s32fc_multiply_32fc.h
/usr/include/volk/volk_32fc_s32fc_rotator2puppet_32fc.h
/usr/include/volk/volk_32fc_s32fc_x2_rotator2_32fc.h
/usr/include/volk/volk_32fc_s32fc_x2_rotator_32fc.h
/usr/include/volk/volk_32fc_x2_add_32fc.h
/usr/include/volk/volk_32fc_x2_conjugate_dot_prod_32fc.h
/usr/include/volk/volk_32fc_x2_divide_32fc.h
/usr/include/volk/volk_32fc_x2_dot_prod_32fc.h
/usr/include/volk/volk_32fc_x2_multiply_32fc.h
/usr/include/volk/volk_32fc_x2_multiply_conjugate_32fc.h
/usr/include/volk/volk_32fc_x2_s32f_square_dist_scalar_mult_32f.h
/usr/include/volk/volk_32fc_x2_s32fc_multiply_conjugate_add2_32fc.h
/usr/include/volk/volk_32fc_x2_s32fc_multiply_conjugate_add_32fc.h
/usr/include/volk/volk_32fc_x2_square_dist_32f.h
/usr/include/volk/volk_32i_s32f_convert_32f.h
/usr/include/volk/volk_32i_x2_and_32i.h
/usr/include/volk/volk_32i_x2_or_32i.h
/usr/include/volk/volk_32u_byteswap.h
/usr/include/volk/volk_32u_byteswappuppet_32u.h
/usr/include/volk/volk_32u_popcnt.h
/usr/include/volk/volk_32u_popcntpuppet_32u.h
/usr/include/volk/volk_32u_reverse_32u.h
/usr/include/volk/volk_64f_convert_32f.h
/usr/include/volk/volk_64f_x2_add_64f.h
/usr/include/volk/volk_64f_x2_max_64f.h
/usr/include/volk/volk_64f_x2_min_64f.h
/usr/include/volk/volk_64f_x2_multiply_64f.h
/usr/include/volk/volk_64u_byteswap.h
/usr/include/volk/volk_64u_byteswappuppet_64u.h
/usr/include/volk/volk_64u_popcnt.h
/usr/include/volk/volk_64u_popcntpuppet_64u.h
/usr/include/volk/volk_8i_convert_16i.h
/usr/include/volk/volk_8i_s32f_convert_32f.h
/usr/include/volk/volk_8ic_deinterleave_16i_x2.h
/usr/include/volk/volk_8ic_deinterleave_real_16i.h
/usr/include/volk/volk_8ic_deinterleave_real_8i.h
/usr/include/volk/volk_8ic_s32f_deinterleave_32f_x2.h
/usr/include/volk/volk_8ic_s32f_deinterleave_real_32f.h
/usr/include/volk/volk_8ic_x2_multiply_conjugate_16ic.h
/usr/include/volk/volk_8ic_x2_s32f_multiply_conjugate_32fc.h
/usr/include/volk/volk_8u_conv_k7_r2puppet_8u.h
/usr/include/volk/volk_8u_x2_encodeframepolar_8u.h
/usr/include/volk/volk_8u_x3_encodepolar_8u_x2.h
/usr/include/volk/volk_8u_x3_encodepolarpuppet_8u.h
/usr/include/volk/volk_8u_x4_conv_k7_r2_8u.h
/usr/include/volk/volk_alloc.hh
/usr/include/volk/volk_avx2_fma_intrinsics.h
/usr/include/volk/volk_avx2_intrinsics.h
/usr/include/volk/volk_avx_intrinsics.h
/usr/include/volk/volk_common.h
/usr/include/volk/volk_complex.h
/usr/include/volk/volk_config_fixed.h
/usr/include/volk/volk_cpu.h
/usr/include/volk/volk_malloc.h
/usr/include/volk/volk_neon_intrinsics.h
/usr/include/volk/volk_prefs.h
/usr/include/volk/volk_sse3_intrinsics.h
/usr/include/volk/volk_sse_intrinsics.h
/usr/include/volk/volk_typedefs.h
/usr/include/volk/volk_version.h
/usr/lib64/cmake/volk/VolkConfig.cmake
/usr/lib64/cmake/volk/VolkConfigVersion.cmake
/usr/lib64/cmake/volk/VolkTargets-relwithdebinfo.cmake
/usr/lib64/cmake/volk/VolkTargets.cmake
/usr/lib64/libvolk.so
/usr/lib64/pkgconfig/volk.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvolk.so.3.1
/usr/lib64/libvolk.so.3.1.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/volk/05c9c329f6de4edcdc6d2e84fa466aaaeef3166f
/usr/share/package-licenses/volk/a8a12e6867d7ee39c21d9b11a984066099b6fb6b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
